# Generated by Django 5.2.7 on 2025-10-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='people',
        ),
    ]
